sudo: required

services:
  - docker

# Test is needed for Client only, can be added more lines like below
before_install: 
  - docker build -t noelroy/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true noelroy/react-test npm test

after_success: 
  - docker build -t noelroy/client ./client
  - docker build -t noelroy/server ./server
  - docker build -t noelroy/worker ./worker
  - docker build -t noelroy/nginx ./nginx
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker_login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push noelroy/client
  - docker push noelroy/server
  - docker push noelroy/worker
  - docker push noelroy/nginx