version: "3"
services:
  # FOR External DBs
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:latest"
  nginx:
    restart: always # this way nginx will always restart if any crash occurs
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80" # localhost:container
    depends_on:
      - api
      - client

  # FOR Server build
  api: # the actual server instance
    build:
      dockerfile: Dockerfile.dev # just mention the file name
      context: ./server # to jsutify the location of the dockerfile
    volumes:
      - /app/node_modules # just leave the folder as it is
      - ./server:/app # copy all files from server -> /app in container
    environment:
      - REDIS_HOST=redis # simply put the name of the service
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres # same as mentioned on services
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  # FOR Client build
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  # FOR Worker build
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
